# Generated by Django 4.1.4 on 2022-12-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='owner',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 - Too bad'), (2, '2 - Bad'), (3, '3 - Normal'), (4, '4 - Good'), (5, '5 - Perfect')]),
        ),
    ]
