# Generated by Django 4.1.4 on 2022-12-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_rating_owner_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
