# Generated by Django 4.1.4 on 2022-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_review_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
